---
swagger: "2.0"
info:
  description: "This is a playground for trying out [Mesibo Backend APIs](https://mesibo.com/documentation/api/backend-api).\n
    \ You need an `Application token` to try the APIs.\
    \ You can get and change the app token from the [Mesibo Console](https://mesibo.com/console).\n
    \ First, Click on the `Authorize` button and fill in the token value.\n
    \ To try an API, click on the API and then click on `Try it out` button"
  version: "1.0"
  title: "Mesibo Backend APIs "
schemes:
    - https
host: "api.mesibo.com"
basePath: ""
tags:
- name: "User Management APIs"
  description: "Create, Edit and Delete Users"
- name: "Group Management APIs"
  description: "Create, Edit Group Members"

  
securityDefinitions:
  AppTokenAuth:
    type: "apiKey"
    name: "token"
    in: "query"

security:
 - AppTokenAuth: []     

paths:
  /api.php?op=useradd:
    post:
      tags:
      - "User Management APIs"
      summary: "Add a User or Regenerate a User Access Token"
      description: "To enable real-time communication between your users, you need to let mesibo know about each of your users. Mesibo will create an access token for each user and give it to you which you can send it to your users. Your user can then use this access token in Mesibo Real-time APIs using setAccessToken function."
      operationId: "useradd"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      # - name: "token"
      #   in: "query"
      #   description: "Application Token obtained from mesibo console"
      #   required: true
      #   type: "string"
      - name: "addr"
        in: "query"
        description: "User Address (e.g phone number, email address, etc.)"
        required: true
        type: "string"
      - name: "appid"
        in: "query"
        description: "Android package name or iOS Bundle id. The generated token will be applicable for the app having this package name or Bundle id only. For all other platforms, you can pass any unique string, and the same need to be passed to `setAppName` function."
        required: true
        type: "string"
      - name: "expiry"
        in: "query"
        description: "in minutes, default 1 year"
        required: false
        type: "integer"
        format: "int64"
        default: 525600
      - name: "active"
        in: "query"
        description: "enable user, default 1 (active) "
        required: false
        type: "integer"
        format: "int64"
        default: 1
      - name: "groups"
        in: "query"
        description: "Maximum Groups"
        required: false
        type: "integer"
        format: "int64"

      responses:
        '200':
          description: A User object

  /api.php?op=userset:
    post:
      tags:
      - "User Management APIs"
      summary: "Edit a User"
      description: "Edit an existing user using the `UID` obtained from `useradd` operation."
      operationId: "userset"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "token"
        in: "query"
        description: "Application Token obtained from mesibo console"
        required: true
        type: "string"
      - name: "uid"
        in: "query"
        description: "User ID obtained in add user operation"
        required: true
        type: "integer"
      - name: "flag"
        in: "query"
        description: "Flags"
        required: true
        type: "string"
      - name: "active"
        in: "query"
        description: "1 to enable, 0 to disable"
        required: true
        type: "integer"                
      responses:
        '200':
          description: A User object          

  /api.php?op=userdel:
    delete:
      tags:
      - "User Management APIs"
      summary: "Delete a User"
      description: "Edit an existing user using the `UID` obtained from `useradd` operation."
      operationId: "userdel"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "token"
        in: "query"
        description: "Application Token obtained from mesibo console"
        required: true
        type: "string"
      - name: "uid"
        in: "query"
        description: "User ID obtained in add user operation"
        required: true
        type: "integer"
      - name: "flag"
        in: "query"
        description: "Flags"
        required: true
        type: "string"
      - name: "active"
        in: "query"
        description: "1 to enable, 0 to disable"
        required: true
        type: "integer"                
      responses:
        '200':
          description: A User object
    put:
      tags:
      - "User Management APIs"
      summary: "Delete a User Access Token without deleting a user"
      description: "Delete an existing user access token without deleting a user. User will be logged-out but will continue to receive messages which will be delivered when user logs-in next time with a new token."
      operationId: "userdelToken"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "token"
        in: "query"
        description: "Application Token obtained from mesibo console"
        required: true
        type: "string"
      - name: "uid"
        in: "query"
        description: "User ID obtained in add user operation"
        required: true
        type: "integer"
      - name: "flag"
        in: "query"
        description: "Flags"
        required: true
        type: "string"
      - name: "active"
        in: "query"
        description: "1 to enable, 0 to disable"
        required: true
        type: "integer"                
      responses:
        '200':
          description: A User object      
   
  /api.php?op=usersget:
    get:
      tags:
      - "User Management APIs"
      summary: "Get Users"
      description: "This API is only for development purpose only and hence maximum 20 users will be returned. You should store your users locally instead of obtaining from the mesibo."
      operationId: "usersget"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "token"
        in: "query"
        description: "Application Token obtained from mesibo console"
        required: true
        type: "string"
      - name: "addr"
        in: "query"
        description: "Get users matching address. Wildcard (*) allowed"
        required: false
        type: "string"
      - name: "count"
        in: "query"
        description: "max number of users to get. Max 20"
        required: false
        type: "integer"
        default: 20            
      responses:
        '200':
          description: A User object