---
swagger: "2.0"
info:
  description: "This is a playground for trying out [Mesibo Backend APIs](https://mesibo.com/documentation/api/backend-api)\
    \ You need an `Application token` to test the APIs.\
    \ You can get and change the app token from the [Mesibo Console](https://mesibo.com/console)."
  version: "1.0"
  title: "Mesibo Backend APIs "
host: "api.mesibo.com"
basePath: "/"
tags:
- name: "User Management APIs"
  description: "Create, Edit and Delete Users"
schemes:
- "https"
- "http"
paths:
  /api.php:
    post:
      tags:
      - "User Management APIs"
      summary: "**useradd** Add a User or Regenerate a User Access Token"
      description: "To enable real-time communication between your users, you need to let mesibo know about each of your users. Mesibo will create an access token for each user and give it to you which you can send it to your users. Your user can then use this access token in Mesibo Real-time APIs using setAccessToken function."
      operationId: "useradd"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "op"
        in: "query"
        description: "Operation to perform"
        required: true
        type: "string"
        default: "useradd"
      - name: "token"
        in: "query"
        description: "Application Token obtained from mesibo console"
        required: true
        type: "string"
      - name: "addr"
        in: "query"
        description: "User Address (e.g phone number, email address, etc.)"
        required: true
        type: "string"
      - name: "appid"
        in: "query"
        description: "Android package name or iOS Bundle id. The generated token will be applicable for the app having this package name or Bundle id only. For all other platforms, you can pass any unique string, and the same need to be passed to `setAppName` function."
        required: true
        type: "string"
      - name: "expiry"
        in: "query"
        description: "in minutes, default 1 year"
        required: false
        type: "integer"
        format: "int64"
        default: 525600
      - name: "active"
        in: "query"
        description: "enable user, default 1 (active) "
        required: false
        type: "integer"
        format: "int64"
        default: 1
      - name: "groups"
        in: "query"
        description: "Maximum Groups"
        required: false
        type: "integer"
        format: "int64"

      responses:
        '200':
          description: A User object
          content:
            application/json:
              schema:
                type: object
                properties:
                  uid:
                    type: integer
                    description: The user ID.
                  token:
                    type: string
                    description: User Access Token.

 